#!/bin/bash
set -e

example=$1

for i in *
do
    if [[ -d $i/QEMU ]]
    then
        examples+=" $i"
    fi
done

if [[ "$example" == "" ]]
then
    for i in $examples
    do
        echo $i
    done
    exit 0
fi

shift
more_options=$*

folder=${example}/QEMU

if [[ -d $folder ]]
then
    cd $folder
else
    echo no such qemu example $example_number
    exit 1
fi

INCLUDES=-Fi/home/gitpod/ultibo/core/fpc/source/packages/fv/src

function build {
    echo ......................... building *.lpr for target $1
    rm -f *.o
    fpc \
     -B \
     -Tultibo \
     -O2 \
     -Parm \
     $2 \
     $INCLUDES \
     @/home/gitpod/ultibo/core/fpc/bin/$3 \
     *.lpr
    set +x
    if [ "$?" != 0 ]
    then
        exit 1
    fi
}

qemu_network_options=""
if [[ $(grep -i winsock2 *.lpr) != "" ]]
then
    qemu_network_options="-net nic -net user,hostfwd=tcp::5080-:80"
fi

build QEMU "-CpARMV7A -WpQEMUVPB" qemuvpb.cfg
qemu-system-arm -m 256M -M versatilepb -cpu cortex-a8 -kernel kernel.bin \
    $qemu_network_options \
    $more_options

