#!/bin/bash
set -e

example_number=$1
shift
more_options=$*

qemu_examples="01-HelloWorld 03-ScreenOutput 04-KeyboardInput 05-TimeDate 06-PascalObjects 07-Exceptions 08-FileHandling 09-LogOutput 10-MultiThreading 12-WebServer 13-SerialConnection 15-MouseCursor 17-TextEditor"

if [[ "$example_number" == "" ]]
then
    for i in $qemu_examples
    do
        echo $i
    done
    exit 0
fi

cd github.com/ultibohub/Examples/${example_number}*/QEMU

INCLUDES=-Fi/home/gitpod/ultibo/core/fpc/source/packages/fv/src

function build {
    echo ......................... building *.lpr for target $1
    rm -f *.o
    set -x
    fpc \
     -B \
     -Tultibo \
     -O2 \
     -Parm \
     $2 \
     $INCLUDES \
     @/home/gitpod/ultibo/core/fpc/bin/$3 \
     *.lpr
    set +x
    if [ "$?" != 0 ]
    then
        exit 1
    fi
}

build QEMU "-CpARMV7A -WpQEMUVPB" qemuvpb.cfg
qemu-system-arm -m 256M -M versatilepb -cpu cortex-a8 -kernel kernel.bin \
    -net nic -net user,hostfwd=tcp::5080-:80 \
    $more_options

